default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [jquery.min.js]

  has_layout:     true
  layout:         layout
