<?php
require 'lib/model/om/BaseArticlePeer.php';
/**
 * Skeleton subclass for performing query and update operations on the 'articles' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Thu Nov 26 14:06:24 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ArticlePeer extends BaseArticlePeer 
{
    
} // ArticlePeer
// lucene searcher
if (sfContext::hasInstance()) {
    sfLucenePropelBehavior::getInitializer()->setup('Article');
}